global using Geren.Generator.Common;
global using Geren.Generator.Emit;
global using Geren.Generator.Incs;
global using Geren.Generator.Map;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Text;
global using Microsoft.OpenApi;
global using System.Collections.Immutable;
global using System.Text;
