namespace Geren.Client.Generator.Emit;

internal static class EmitExtensions {
    internal static string Run(string rootNamespace, string namespaceFromFile, IEnumerable<string> names) {
        return $$"""
#nullable enable
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http.Resilience;
using Polly;
using System;

namespace {{rootNamespace}}.{{namespaceFromFile}};

/// <summary>
/// Extension methods to register Geren-generated <see cref="HttpClient"/> API clients.
/// </summary>
/// <remarks>
/// This type is generated by Geren from an OpenAPI document.
/// Prefer calling <see cref="AddGerenClients(IServiceCollection, Action{HttpClient}?, Action{IHttpClientBuilder}?, bool, string?, Action{ResiliencePipelineBuilder{HttpResponseMessage}, ResilienceHandlerContext}?)}.
/// </remarks>
public static class {{namespaceFromFile.Replace('.', '_')}}_Extensions
{
    /// <summary>
    /// Registers all generated clients from this OpenAPI document into DI.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional <see cref="HttpClient"/> configuration applied to all clients.</param>
    /// <param name="clientBuilder">Optional per-client <see cref="IHttpClientBuilder"/> customization applied to all clients.</param>
    /// <param name="useResilience">When true, configures a resilience handler for all clients.</param>
    /// <param name="resiliencePipelineName">Optional resilience pipeline name (used when <paramref name="configureResilience"/> is provided).</param>
    /// <param name="configureResilience">Optional resilience pipeline configuration.</param>
    /// <returns>The input <paramref name="services"/> (for chaining).</returns>
    public static IServiceCollection AddGerenClients(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null,
        Action<IHttpClientBuilder>? clientBuilder = null,
        bool useResilience = true,
        string? resiliencePipelineName = null,
        Action<ResiliencePipelineBuilder<HttpResponseMessage>, ResilienceHandlerContext>? configureResilience = null)
    {
{{AllReg()}}
        return services;
    }

{{SingleReg()}}
}
""";

        string AllReg() => string.Join(Given.NewLine, names.Select(name => $$"""
        global::{{rootNamespace}}.FactoryBridge.AddClient<{{name}}>(services, configureClient, clientBuilder, useResilience, resiliencePipelineName, configureResilience);
"""));

        // Registration for each class
        string SingleReg() => string.Join(Given.NewLine + Given.NewLine, names.Select(name => $$"""
    /// <summary>
    /// Registers the <see cref="{{name}}"/> API client into DI.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional <see cref="HttpClient"/> configuration.</param>
    /// <returns>The created <see cref="IHttpClientBuilder"/> for further configuration.</returns>
    public static IHttpClientBuilder AddGeren{{name.Replace(".", "_")}}(this IServiceCollection services,
        Action<HttpClient>? configureClient = null) => global::{{rootNamespace}}.FactoryBridge.AddClient<{{name}}>(services, configureClient);
"""));
    }
}
