namespace Geren.Client.Generator.Emit;

internal sealed class EmitClient {
    internal static string Run(IGrouping<object, Mapoint> endpoints, string rootNamespace, string spaceName, string className) => $$"""
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;

namespace {{spaceName}};

/// <summary>
/// A typed API client generated by Geren.
/// </summary>
/// <remarks>
/// This type is generated from an OpenAPI document. Methods call the corresponding HTTP endpoints.
/// </remarks>
public sealed partial class {{className}} : GerenClientBase
{
    /// <summary>
    /// Creates a new API client instance.
    /// </summary>
    /// <param name="http">The underlying <see cref="HttpClient"/> used to send requests.</param>
    public {{className}}(HttpClient http) : base(http) { }

    /// <summary>
    /// Creates a new API client instance with per-request hooks resolved from DI.
    /// </summary>
    /// <param name="http">The underlying <see cref="HttpClient"/> used to send requests.</param>
    /// <param name="services">Service provider used to resolve optional hooks (see <see cref="global::Geren.IGerenClientRequestHooks"/>).</param>
    [global::Microsoft.Extensions.DependencyInjection.ActivatorUtilitiesConstructor]
    public {{className}}(HttpClient http, System.IServiceProvider services) : base(http, services) { }

{{string.Join(Given.NewLine + Given.NewLine, endpoints.Select(EmitMethod))}}
}
""";

    private static string EmitMethod(Mapoint endpoint) {
        var args = string.Join(", ", endpoint.Params.Concat(endpoint.Queries).Select(p => $"{p.Type} {p.Identifier ?? p.Name}"));
        if (args.Length > 0)
            args += ", ";

        if (endpoint.Method is Givens.Post or Givens.Put or Givens.Patch)
            args += $"{endpoint.BodyType ?? "string"} body, ";

        var signature = $"{endpoint.MethodName}({args}CancellationToken cancellationToken = default)";
        var pathExpr = BuildPathExpression(endpoint);
        if (endpoint.Method is Givens.Get or Givens.Delete)
            return EmitGetDelete(endpoint, signature, pathExpr);

        return EmitPostOrPutOrPatch(endpoint, signature, pathExpr);
    }

    private static string EmitGetDelete(Mapoint endpoint, string signature, string pathExpr) {
        var doc = EmitDocComment(endpoint);
        // void
        if (string.IsNullOrEmpty(endpoint.ReturnType)) {
            return $$"""
{{doc}}
    public async Task {{signature}}
    {
        var path = {{pathExpr}};
        using var request = new HttpRequestMessage({{HttpMethodExpr(endpoint)}}, path);
        PrepareRequest(request);

        using var response = await Http.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();
    }
""";
        }

        // ReadAsString
        if (endpoint.ReturnType == "string") {
            return $$"""
{{doc}}
    public async Task<string> {{signature}}
    {
        var path = {{pathExpr}};
        using var request = new HttpRequestMessage({{HttpMethodExpr(endpoint)}}, path);
        PrepareRequest(request);

        using var response = await Http.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }
""";
        }

        // FromJson
        return $$"""
{{doc}}
    public async Task<{{endpoint.ReturnType}}> {{signature}}
    {
        var path = {{pathExpr}};
        using var request = new HttpRequestMessage({{HttpMethodExpr(endpoint)}}, path);
        PrepareRequest(request);

        using var response = await Http.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<{{endpoint.ReturnType}}>(JsonOptions, cancellationToken);
    }
""";
    }

    private static string EmitPostOrPutOrPatch(Mapoint endpoint, string signature, string pathExpr) {
        var doc = EmitDocComment(endpoint);
        string method = HttpMethodExpr(endpoint);

        if (endpoint.BodyMedia == MediaTypes.Application_Json) {
            return EmitResponse(doc, signature, endpoint.ReturnType, $$"""
        var path = {{pathExpr}};
        using var request = new HttpRequestMessage({{method}}, path)
        {
            Content = JsonContent.Create(body, options: JsonOptions)
        };
        PrepareRequest(request);

        using var response = await Http.SendAsync(request, cancellationToken);
""");
        }

        // text/plain
        return EmitResponse(doc, signature, endpoint.ReturnType, $$"""
        var path = {{pathExpr}};
        using var request = new HttpRequestMessage({{method}}, path)
        {
            Content = new StringContent(body, Encoding.UTF8, "text/plain")
        };
        PrepareRequest(request);

        using var response = await Http.SendAsync(request, cancellationToken);
""");
    }

    private static string EmitResponse(string doc, string signature, string? returnType, string send) {
        // void
        if (string.IsNullOrEmpty(returnType)) {
            return $$"""
{{doc}}
    public async Task {{signature}}
    {
{{send}}
        response.EnsureSuccessStatusCode();
    }
""";
        }

        // ReadAsString
        if (returnType == "string") {
            return $$"""
{{doc}}
    public async Task<string> {{signature}}
    {
{{send}}
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadAsStringAsync(cancellationToken);
    }
""";
        }

        // FromJson
        return $$"""
{{doc}}
    public async Task<{{returnType}}> {{signature}}
    {
{{send}}
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<{{returnType}}>(JsonOptions, cancellationToken);
    }
""";
    }
    private static string BuildPathExpression(Mapoint endpoint) {
        string interpolatedPath = endpoint.Path;
        foreach (var param in endpoint.Params)
            interpolatedPath = interpolatedPath.Replace("{" + param.Name + "}", "{FormatPathValue(" + (param.Identifier ?? param.Name) + ")}");

        string pathExpr = $"$\"{interpolatedPath}\"";
        if (endpoint.Queries.IsEmpty)
            return pathExpr;

        string queryBuilder = string.Join(Given.NewLine, endpoint.Queries.Select(static p =>
            $"            AddQueryParameter(query, \"{p.Name}\", {p.Identifier});"));

        return $$"""
BuildRequestUri({{pathExpr}}, query =>
        {
{{queryBuilder}}
        })
""";
    }

    private static string EmitDocComment(Mapoint endpoint) {
        static string Escape(string? s) => (s ?? string.Empty)
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

        var sb = new StringBuilder();
        sb.Append("    /// <summary>").Append(Given.NewLine);
        sb.Append("    /// Calls <c>").Append(endpoint.Method).Append("</c> <c>")
            .Append(Escape(endpoint.Path)).Append("</c>.").Append(Given.NewLine);
        sb.Append("    /// </summary>").Append(Given.NewLine);
        sb.Append("    /// <exception cref=\"HttpRequestException\">The HTTP response status code is not successful.</exception>").Append(Given.NewLine);

        foreach (var p in endpoint.Params) {
            sb.Append("    /// <param name=\"").Append(p.Identifier ?? p.Name).Append("\">Route parameter <c>")
                .Append(Escape(p.Name)).Append("</c>.</param>").Append(Given.NewLine);
        }

        foreach (var q in endpoint.Queries) {
            sb.Append("    /// <param name=\"").Append(q.Identifier ?? q.Name).Append("\">Query parameter <c>")
                .Append(Escape(q.Name)).Append("</c>.</param>").Append(Given.NewLine);
        }

        if (endpoint.Method is Givens.Post or Givens.Put or Givens.Patch) {
            sb.Append("    /// <param name=\"body\">Request body.</param>").Append(Given.NewLine);
        }

        sb.Append("    /// <param name=\"cancellationToken\">Cancellation token.</param>").Append(Given.NewLine);

        if (string.IsNullOrEmpty(endpoint.ReturnType)) {
            sb.Append("    /// <returns>A task that completes when the request finishes successfully.</returns>").Append(Given.NewLine);
        }
        else if (endpoint.ReturnType == "string") {
            sb.Append("    /// <returns>The response body as a string.</returns>").Append(Given.NewLine);
        }
        else {
            sb.Append("    /// <returns>The deserialized JSON response (see <see cref=\"GerenClientBase.JsonOptions\"/>).</returns>").Append(Given.NewLine);
        }

        return sb.ToString().TrimEnd();
    }

    private static string HttpMethodExpr(Mapoint endpoint)
        => endpoint.Method switch
        {
            Givens.Get => "HttpMethod.Get",
            Givens.Post => "HttpMethod.Post",
            Givens.Put => "HttpMethod.Put",
            Givens.Patch => "HttpMethod.Patch",
            Givens.Delete => "HttpMethod.Delete",
            _ => "new HttpMethod(\"" + endpoint.Method + "\")",
        };
}
